PLUG_IP = "255.255.255.255"
PLUG_MAC = "AA:BB:CC:DD:EE:FF"

PUSHOVER_USER_KEY = "your_user_key_here"
PUSHOVER_APP_TOKEN = "your_app_token_here"

DO_CALIBRATION_CYCLES = True
CALIBRATION_CYCLES = 3
CALIBRATION_STATE_FILE = "calibration_done.flag"

CALIBRATION_CHARGE_TO = 100
CALIBRATION_DISCHARGE_TO = 15
CALIBRATION_POLL_SECONDS = 30
CALIBRATION_MAX_CHARGE_SECONDS = 6 * 60 * 60      # 6 hours
CALIBRATION_MAX_DISCHARGE_SECONDS = 8 * 60 * 60   # 8 hours
CALIBRATION_MIN_CHARGE_RATE = 1                   # must gain 1% over window
CALIBRATION_STALL_WINDOW = 15 * 60                # 15 minutes
CALIBRATION_HARD_FLOOR = 10                       # emergency floor %
CALIBRATION_HOLD_FOR = 30 * 60                    # 30 minutes
CALIBRATION_PUSH_ON_COMPLETE = True

NORMAL_CHARGE_ON_BELOW = 25
NORMAL_CHARGE_OFF_ABOVE = 85

HIBERNATE_THRESHOLD = 15
VIGILANCE_MIN_PERCENT = 10
VIGILANCE_MAX_PERCENT = 20
VIGILANCE_GRACE_SECONDS = 5

CHARGE_FAILURE_DELTA = 2

LOG_FILE = "battery_charge_controller.log"
