PLUG_MAC = "AA:BB:CC:DD:EE:FF"

PUSHOVER_USER_KEY = "your_user_key_here"
PUSHOVER_APP_TOKEN = "your_app_token_here"

DO_CALIBRATION_CYCLES = True
CALIBRATION_CYCLES = 3
CALIBRATION_STATE_FILE = "calibration_done.flag"

CALIBRATION_CHARGE_TO = 100
CALIBRATION_DISCHARGE_TO = 15
CALIBRATION_POLL_SECONDS = 30

NORMAL_CHARGE_ON_BELOW = 25
NORMAL_CHARGE_OFF_ABOVE = 85

HIBERNATE_THRESHOLD = 15
VIGILANCE_MIN_PERCENT = 10
VIGILANCE_MAX_PERCENT = 20
VIGILANCE_GRACE_SECONDS = 5

LOG_FILE = "battery_charge_controller.log"
